---
abstract: 'Simple interface to block delivery of signals'
author:
  - 'Michael Schout <mschout@cpan.org>'
build_requires:
  Test::Exception: '0'
  Test::More: '0'
  lib: '0'
  perl: '5.008'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.008'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.010, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Sys-Signals-Block
provides:
  Sys::Signals::Block:
    file: lib/Sys/Signals/Block.pm
    version: '0.11'
requires:
  Carp: '0'
  Moo: '0'
  MooX::ClassAttribute: '0'
  POSIX: '0'
  namespace::clean: '0'
  perl: '5.008'
  strict: '0'
  strictures: '2'
  warnings: '0'
resources:
  bugtracker: https://github.com/mschout/sys-signals-block/issues
  homepage: https://github.com/mschout/sys-signals-block
  repository: https://github.com/mschout/sys-signals-block.git
version: '0.11'
x_serialization_backend: 'YAML::Tiny version 1.70'
